apps/blogs/urls.py
from django.conf.urls import url, patterns
from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.FeedView.as_view(), name='feed'),
    url(r'^my/$', views.PostListView.as_view(), name='post_list'),
    url(r'^my/create/$', views.PostCreateView.as_view(), name='post_create'),
    url(r'^(?P<blog_pk>\d+)/$', views.PostListView.as_view(),
        name='post_list'),
    url(r'^(?P<blog_pk>\d+)/follow/$', views.follow, name='follow'),
    url(r'^(?P<blog_pk>\d+)/unfollow/$', views.unfollow, name='unfollow'),
    url(r'^(?P<blog>\d+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(),
        name='post_detail'),
    url(r'^(?P<blog>\d+)/(?P<pk>\d+)/watch/$', views.mark_post_watched,
        name='mark_post_watched'),
)

project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blogs.urls', namespace='blogs')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
        url(r'^500/$', TemplateView.as_view(template_name='500.html')),
        url(r'^t/(.*)$', 'django.shortcuts.render'),
    )

apps/blogs/models.py
# coding: utf-8

from datetime import datetime

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.dispatch import receiver

from annoying.fields import AutoOneToOneField

from .notifications import send_notifications


User = settings.AUTH_USER_MODEL


class Blog(models.Model):

    user = AutoOneToOneField(User, related_name='blog')
    followers = models.ManyToManyField(User, related_name='favorite_blogs')

    def __unicode__(self):
        return u'Блог пользователя {}'.format(self.user)

    @models.permalink
    def get_absolute_url(self):
        return ('blog:post_list', (), {'blog_pk': self.pk})


class PostQuerySet(models.query.QuerySet):

    def in_blog(self, blog):
        return self.filter(blog=blog)


class Post(models.Model):

    blog = models.ForeignKey(Blog, related_name='posts')

    title = models.CharField(u'заголовок', max_length=255)
    text = models.TextField(u'текст')
    created_at = models.DateTimeField(default=datetime.now)
    watched_by = models.ManyToManyField(User, related_name='watched_posts')

    objects = PostQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']

    def __unicode__(self):
        return self.title

    def is_watched(self, user):
        return self.watched_by.filter(pk=user.pk).exists()

    def mark_watched(self, user):
        watch_obj = self.watched_by.add(user)

    @models.permalink
    def get_absolute_url(self):
        return ('blog:post_detail', (), {'blog_pk': self.blog_id, 'pk': self.pk})


@receiver(models.signals.post_save, sender=Post)
def notify_blog_followers(sender, instance, **kwargs):
    if not kwargs.get('created') or kwargs.get('raw', False):
        return
    send_notifications(instance)

apps/blogs/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

apps/blogs/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView
from django.views.decorators.http import require_POST

from .favorites import get_posts_in_feed, follow, unfollow
from .forms import PostForm
from .models import Post, Blog


class LoginRequiredMixin(object):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class BlogMixin(LoginRequiredMixin):

    model = Post

    def get_blog(self):
        if 'blog_pk' in self.kwargs:
            return get_object_or_404(Blog, pk=self.kwargs.get('blog_pk'))
        return self.request.user.blog

    def get(self, request, *args, **kwargs):
        self.blog = self.get_blog()
        return super(BlogMixin, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return Post.objects.in_blog(self.blog)

    def get_context_data(self, **kwargs):
        kwargs.update({'blog': self.blog})
        return super(BlogMixin, self).get_context_data(**kwargs)


class PostListView(BlogMixin, ListView):

    pass


class PostDetailView(BlogMixin, DetailView):

    pass


class FeedView(LoginRequiredMixin, ListView):

    template_name = 'blogs/feed.html'

    def get_queryset(self):
        return get_posts_in_feed(self.request.user)


class PostCreateView(BlogMixin, CreateView):

    form_class = PostForm
    model = Post

    def get_blog(self):
        return self.request.user.blog

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.blog = self.blog
        self.object.save()
        return redirect(self.get_success_url())


@login_required
@require_POST
def mark_post_watched(self):
    post_pk = self.request.POST.get('post_pk')
    post = get_object_or_404(Post, pk=post_pk)
    post.mark_watched(self.request.user)
    return redirect('blog:feed')


@login_required
@require_POST
def follow(self, blog_pk):
    blog = get_object_or_404(Blog, pk=post_pk)
    follow(user, blog)
    return redirect(blog.get_absolute_url())


@login_required
@require_POST
def unfollow(self, blog_pk):
    blog = get_object_or_404(Blog, pk=post_pk)
    unfollow(user, blog)
    return redirect(blog.get_absolute_url())

project/templates/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blogs for devhub</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">DevHub</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'blogs:feed' %}">Лента новостей</a></li>
            <li><a href="{% url 'blogs:post_list' %}">Мой блог</a></li>
            <li><a href="#?">Блоги других пользователей</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

    {% block content %}
    {% endblock %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

project/templates/blogs/feed.html
{% extends "base.html" %}

{% block content %}
<div class="feed">
  {% for object in object_list %}
  <div class="post">
    <div class="item">
      <a class="link" href="{{ object.get_absolute_url }}">{{ object.title }}</a> от {{ object.created_at }}<br>
      В блоге <a class="link" href="{{ object.blog.get_absolute_url }}">{{ object.blog }}</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}